spring.application.name=backend
server.port=8080

# DataSource
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres:5432/umsoft_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:1111}

# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.yandex.ru

# GigaChat
gigachat.api.auth-key=${GIGACHAT_API_KEY}
gigachat.api.scope=GIGACHAT_API_PERS
gigachat.api.verify-ssl=false

logging.level.com.umsoft.backend=DEBUG